services:
  backend:
    container_name: vacare-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
    env_file:
      - ./docker/.env.production
    environment:
      DATABUTTON_SERVICE_TYPE: prodx
      PORT: ${BACKEND_PORT:-8000}
    ports:
      - "${BACKEND_PORT:-8000}:8000"
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -fsS http://127.0.0.1:${PORT:-8000}/docs || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - vacare

  frontend:
    container_name: vacare-frontend
    build:
      context: .
      dockerfile: Dockerfile.frontend
      args:
        DATABUTTON_PROJECT_ID: ${DATABUTTON_PROJECT_ID}
        DATABUTTON_EXTENSIONS: ${DATABUTTON_EXTENSIONS}
        VITE_API_URL: ${VITE_API_URL:-/routes}
        VITE_WS_API_URL: ${VITE_WS_API_URL:-}
    depends_on:
      backend:
        condition: service_started
    ports:
      - "${FRONTEND_PORT:-80}:80"
    restart: unless-stopped
    networks:
      - vacare

networks:
  vacare:
    driver: bridge
