version: '3.8'

services:
  va-care:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    environment:
      - DATABUTTON_PROJECT_ID=e450d618-b3ca-4f0d-8025-e82ad27b100e
      - FIREBASE_PROJECT_ID=vacare-1abb5
      - FIREBASE_API_KEY=AIzaSyBtGtKZgMR_kuqyGcG2iHP7BH9WjAhnQeU
      - FIREBASE_AUTH_DOMAIN=vacare-1abb5.firebaseapp.com
      - FIREBASE_STORAGE_BUCKET=vacare-1abb5.firebasestorage.app
      - FIREBASE_MESSAGING_SENDER_ID=881187333959
      - FIREBASE_APP_ID=1:881187333959:web:e6def9c68cbf8d13f14e62
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - va-care-network

  # Development mode with hot reload
  va-care-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev
      target: development
    ports:
      - "3000:3000"  # Frontend dev server
      - "8000:8000"  # Backend API
    environment:
      - NODE_ENV=development
      - DATABUTTON_PROJECT_ID=e450d618-b3ca-4f0d-8025-e82ad27b100e
    volumes:
      - ./frontend:/app/frontend
      - ./backend:/app/backend
      - /app/frontend/node_modules
      - /app/backend/__pycache__
    restart: unless-stopped
    networks:
      - va-care-network
    profiles:
      - dev

  # Redis for caching (optional)
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - va-care-network
    profiles:
      - cache

  # PostgreSQL for additional data storage (optional)
  postgres:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: vacare
      POSTGRES_USER: vacare
      POSTGRES_PASSWORD: vacare_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - va-care-network
    profiles:
      - database

volumes:
  redis_data:
  postgres_data:

networks:
  va-care-network:
    driver: bridge
