
// THIS FILE IS AUTOGENERATED WHEN PAGES ARE UPDATED
import { lazy } from "react";
import { RouteObject } from "react-router-dom";


import { UserGuard } from "app";



const AbilityResults = lazy(() => import("./pages/AbilityResults.tsx"));
const AbilitySelection = lazy(() => import("./pages/AbilitySelection.tsx"));
const AbilityTestResult = lazy(() => import("./pages/AbilityTestResult.tsx"));
const App = lazy(() => import("./pages/App.tsx"));
const ArtsHumanitiesKnowledgeTest = lazy(() => import("./pages/ArtsHumanitiesKnowledgeTest.tsx"));
const Assessment = lazy(() => import("./pages/Assessment.tsx"));
const AssessmentResults = lazy(() => import("./pages/AssessmentResults.tsx"));
const BusinessManagementKnowledgeTest = lazy(() => import("./pages/BusinessManagementKnowledgeTest.tsx"));
const CognitiveAbilityTest = lazy(() => import("./pages/CognitiveAbilityTest.tsx"));
const CommunicationsKnowledgeTest = lazy(() => import("./pages/CommunicationsKnowledgeTest.tsx"));
const ComplexProblemSolvingSkillsTest = lazy(() => import("./pages/ComplexProblemSolvingSkillsTest.tsx"));
const ContentSkillsTest = lazy(() => import("./pages/ContentSkillsTest.tsx"));
const EducationTrainingKnowledgeTest = lazy(() => import("./pages/EducationTrainingKnowledgeTest.tsx"));
const EngineeringTechnologyKnowledgeTest = lazy(() => import("./pages/EngineeringTechnologyKnowledgeTest.tsx"));
const HealthServicesKnowledgeTest = lazy(() => import("./pages/HealthServicesKnowledgeTest.tsx"));
const KnowledgeResults = lazy(() => import("./pages/KnowledgeResults.tsx"));
const KnowledgeSelection = lazy(() => import("./pages/KnowledgeSelection.tsx"));
const KnowledgeTest = lazy(() => import("./pages/KnowledgeTest.tsx"));
const KnowledgeTestResult = lazy(() => import("./pages/KnowledgeTestResult.tsx"));
const LawSafetyKnowledgeTest = lazy(() => import("./pages/LawSafetyKnowledgeTest.tsx"));
const Login = lazy(() => import("./pages/Login.tsx"));
const Logout = lazy(() => import("./pages/Logout.tsx"));
const ManufacturingProductionKnowledgeTest = lazy(() => import("./pages/ManufacturingProductionKnowledgeTest.tsx"));
const MathScienceKnowledgeTest = lazy(() => import("./pages/MathScienceKnowledgeTest.tsx"));
const PhysicalAbilityTest = lazy(() => import("./pages/PhysicalAbilityTest.tsx"));
const ProcessSkillsTest = lazy(() => import("./pages/ProcessSkillsTest.tsx"));
const Profile = lazy(() => import("./pages/Profile.tsx"));
const PsychomotorAbilityTest = lazy(() => import("./pages/PsychomotorAbilityTest.tsx"));
const ResourceManagementSkillsTest = lazy(() => import("./pages/ResourceManagementSkillsTest.tsx"));
const Results = lazy(() => import("./pages/Results.tsx"));
const SensoryAbilityTest = lazy(() => import("./pages/SensoryAbilityTest.tsx"));
const SkillResults = lazy(() => import("./pages/SkillResults.tsx"));
const SkillSelection = lazy(() => import("./pages/SkillSelection.tsx"));
const SocialSkillsTest = lazy(() => import("./pages/SocialSkillsTest.tsx"));
const SystemsSkillsTest = lazy(() => import("./pages/SystemsSkillsTest.tsx"));
const TechnicalSkillsTest = lazy(() => import("./pages/TechnicalSkillsTest.tsx"));
const TransportationKnowledgeTest = lazy(() => import("./pages/TransportationKnowledgeTest.tsx"));
const AdminTuning = lazy(() => import("./pages/AdminTuning.tsx"));

export const userRoutes: RouteObject[] = [



	{ path: "/ability-results", element: <UserGuard><AbilityResults /></UserGuard>},
	{ path: "/abilityresults", element: <UserGuard><AbilityResults /></UserGuard>},
	{ path: "/ability-selection", element: <UserGuard><AbilitySelection /></UserGuard>},
	{ path: "/abilityselection", element: <UserGuard><AbilitySelection /></UserGuard>},
	{ path: "/ability-test-result", element: <UserGuard><AbilityTestResult /></UserGuard>},
	{ path: "/abilitytestresult", element: <UserGuard><AbilityTestResult /></UserGuard>},
	{ path: "/", element: <App />},
	{ path: "/arts-humanities-knowledge-test", element: <UserGuard><ArtsHumanitiesKnowledgeTest /></UserGuard>},
	{ path: "/artshumanitiesknowledgetest", element: <UserGuard><ArtsHumanitiesKnowledgeTest /></UserGuard>},
	{ path: "/assessment", element: <UserGuard><Assessment /></UserGuard>},
	{ path: "/assessment-results", element: <UserGuard><AssessmentResults /></UserGuard>},
	{ path: "/assessmentresults", element: <UserGuard><AssessmentResults /></UserGuard>},
	{ path: "/business-management-knowledge-test", element: <UserGuard><BusinessManagementKnowledgeTest /></UserGuard>},
	{ path: "/businessmanagementknowledgetest", element: <UserGuard><BusinessManagementKnowledgeTest /></UserGuard>},
	{ path: "/cognitive-ability-test", element: <UserGuard><CognitiveAbilityTest /></UserGuard>},
	{ path: "/cognitiveabilitytest", element: <UserGuard><CognitiveAbilityTest /></UserGuard>},
	{ path: "/communications-knowledge-test", element: <UserGuard><CommunicationsKnowledgeTest /></UserGuard>},
	{ path: "/communicationsknowledgetest", element: <UserGuard><CommunicationsKnowledgeTest /></UserGuard>},
	{ path: "/complex-problem-solving-skills-test", element: <UserGuard><ComplexProblemSolvingSkillsTest /></UserGuard>},
	{ path: "/complexproblemsolvingskillstest", element: <UserGuard><ComplexProblemSolvingSkillsTest /></UserGuard>},
	{ path: "/content-skills-test", element: <UserGuard><ContentSkillsTest /></UserGuard>},
	{ path: "/contentskillstest", element: <UserGuard><ContentSkillsTest /></UserGuard>},
	{ path: "/education-training-knowledge-test", element: <UserGuard><EducationTrainingKnowledgeTest /></UserGuard>},
	{ path: "/educationtrainingknowledgetest", element: <UserGuard><EducationTrainingKnowledgeTest /></UserGuard>},
	{ path: "/engineering-technology-knowledge-test", element: <UserGuard><EngineeringTechnologyKnowledgeTest /></UserGuard>},
	{ path: "/engineeringtechnologyknowledgetest", element: <UserGuard><EngineeringTechnologyKnowledgeTest /></UserGuard>},
	{ path: "/health-services-knowledge-test", element: <UserGuard><HealthServicesKnowledgeTest /></UserGuard>},
	{ path: "/healthservicesknowledgetest", element: <UserGuard><HealthServicesKnowledgeTest /></UserGuard>},
	{ path: "/knowledge-results", element: <UserGuard><KnowledgeResults /></UserGuard>},
	{ path: "/knowledgeresults", element: <UserGuard><KnowledgeResults /></UserGuard>},
	{ path: "/knowledge-selection", element: <UserGuard><KnowledgeSelection /></UserGuard>},
	{ path: "/knowledgeselection", element: <UserGuard><KnowledgeSelection /></UserGuard>},
	{ path: "/knowledge-test", element: <UserGuard><KnowledgeTest /></UserGuard>},
	{ path: "/knowledgetest", element: <UserGuard><KnowledgeTest /></UserGuard>},
	{ path: "/knowledge-test-result", element: <UserGuard><KnowledgeTestResult /></UserGuard>},
	{ path: "/knowledgetestresult", element: <UserGuard><KnowledgeTestResult /></UserGuard>},
	{ path: "/law-safety-knowledge-test", element: <UserGuard><LawSafetyKnowledgeTest /></UserGuard>},
	{ path: "/lawsafetyknowledgetest", element: <UserGuard><LawSafetyKnowledgeTest /></UserGuard>},
	{ path: "/login", element: <Login />},
	{ path: "/logout", element: <UserGuard><Logout /></UserGuard>},
	{ path: "/manufacturing-production-knowledge-test", element: <UserGuard><ManufacturingProductionKnowledgeTest /></UserGuard>},
	{ path: "/manufacturingproductionknowledgetest", element: <UserGuard><ManufacturingProductionKnowledgeTest /></UserGuard>},
	{ path: "/math-science-knowledge-test", element: <UserGuard><MathScienceKnowledgeTest /></UserGuard>},
	{ path: "/mathscienceknowledgetest", element: <UserGuard><MathScienceKnowledgeTest /></UserGuard>},
	{ path: "/physical-ability-test", element: <UserGuard><PhysicalAbilityTest /></UserGuard>},
	{ path: "/physicalabilitytest", element: <UserGuard><PhysicalAbilityTest /></UserGuard>},
	{ path: "/process-skills-test", element: <UserGuard><ProcessSkillsTest /></UserGuard>},
	{ path: "/processskillstest", element: <UserGuard><ProcessSkillsTest /></UserGuard>},
	{ path: "/profile", element: <UserGuard><Profile /></UserGuard>},
	{ path: "/psychomotor-ability-test", element: <UserGuard><PsychomotorAbilityTest /></UserGuard>},
	{ path: "/psychomotorabilitytest", element: <UserGuard><PsychomotorAbilityTest /></UserGuard>},
	{ path: "/resource-management-skills-test", element: <UserGuard><ResourceManagementSkillsTest /></UserGuard>},
	{ path: "/resourcemanagementskillstest", element: <UserGuard><ResourceManagementSkillsTest /></UserGuard>},
	{ path: "/results", element: <UserGuard><Results /></UserGuard>},
	{ path: "/sensory-ability-test", element: <UserGuard><SensoryAbilityTest /></UserGuard>},
	{ path: "/sensoryabilitytest", element: <UserGuard><SensoryAbilityTest /></UserGuard>},
	{ path: "/skill-results", element: <UserGuard><SkillResults /></UserGuard>},
	{ path: "/skillresults", element: <UserGuard><SkillResults /></UserGuard>},
	{ path: "/skill-selection", element: <UserGuard><SkillSelection /></UserGuard>},
	{ path: "/skillselection", element: <UserGuard><SkillSelection /></UserGuard>},
	{ path: "/social-skills-test", element: <UserGuard><SocialSkillsTest /></UserGuard>},
	{ path: "/socialskillstest", element: <UserGuard><SocialSkillsTest /></UserGuard>},
	{ path: "/systems-skills-test", element: <UserGuard><SystemsSkillsTest /></UserGuard>},
	{ path: "/systemsskillstest", element: <UserGuard><SystemsSkillsTest /></UserGuard>},
	{ path: "/technical-skills-test", element: <UserGuard><TechnicalSkillsTest /></UserGuard>},
	{ path: "/technicalskillstest", element: <UserGuard><TechnicalSkillsTest /></UserGuard>},
	{ path: "/transportation-knowledge-test", element: <UserGuard><TransportationKnowledgeTest /></UserGuard>},
	{ path: "/transportationknowledgetest", element: <UserGuard><TransportationKnowledgeTest /></UserGuard>},
	{ path: "/admin-tuning", element: <UserGuard><AdminTuning /></UserGuard>},

];
